# Site
title: "Quokka"
bio: "A customisable keystroke launcher with plugins"
description: "A customisable keystroke launcher with plugins"
logo: "https://raw.githubusercontent.com/Faeq-F/Quokka/gh-pages/_layouts/Quokka.png"
locale: en_GB
#url: https://faeq-f.github.io/Quokka
github_username: faeq-f
github: [metadata]

#fix for github pages css
baseurl: /Quokka
url: http://faeq-f.github.io

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: white
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed

# Social
#google:
#plus:            #username
#analytics:
#verify:
#ad-client:
#ad-slot:
#bing-verify:
email: faeqfaisal@hotmail.co.uk
github-url: faeq-F/Quokka
stackoverflow: 13165763/faeq
linkedin: faeq
#xing:              username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
  base_url: https://github.com

exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
  ]
