import { defineStore } from "pinia";

export const usePluginsStore = defineStore("pluginsStore", {
  state: () => ({
    name: "Plugins",
    description: "The plugins for Quokka",
    pluginsList: [
      {
        name: "Installed Apps",
        shortDescription: "Launch apps installed on your machine",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "box",
      },
      {
        name: "Portable Apps",
        shortDescription: "Launch portable applications stored in a given directory",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "usb",
      },
      {
        name: "Everything",
        shortDescription: "Search through and find files and folders",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "folder-search",
      },
      {
        name: "Calculator",
        shortDescription: "Calculate mathematical expressions",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "calculator",
      },
      {
        name: "Power Commands",
        shortDescription: "Shutdown, restart, set to sleep, sign out of and lock your PC",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "power",
      },
      {
        name: "English Dictionary",
        shortDescription: "Find denotations for words in the English (US) language",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "book-a",
      },
      {
        name: "Plugin 7",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 8",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 9",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 10",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 11",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 12",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 13",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 14",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 15",
        shortDescription: "This is the first plugin",
        version: "1.0.0",
        github: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Faeq",
        authorUrl: "faeq-f.github.io",
        icon: "https://example.com/plugin1/icon.png",
      },
    ],
  }),
  actions: {
    getTopPlugins() {
      return this.pluginsList.slice(0, 9);
    },
  },
});
