export const usePluginsStore = defineStore("pluginsStore", {
  state: () => ({
    name: "Plugins",
    description: "The plugins for Quokka",
    pluginsList: [
      {
        name: "Installed Apps",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Portable Apps",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Everything",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Calculator",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 5",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 6",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 7",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 8",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 9",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 10",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 11",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 12",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 13",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 14",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
      {
        name: "Plugin 15",
        description: "This is the first plugin",
        version: "1.0.0",
        website: "https://example.com/plugin1",
        downloadUrl: "https://example.com/plugin1/download",
        author: "Author 1",
        authorUrl: "https://example.com/author1",
        icon: "https://example.com/plugin1/icon.png",
      },
    ],
  }),
  actions: {
    test() {
      console.log("test action called");
    },
  },
});
