### YamlMime:ManagedReference
items:
- uid: Plugin_PortableApps.Settings
  commentId: T:Plugin_PortableApps.Settings
  id: Settings
  parent: Plugin_PortableApps
  children:
  - Plugin_PortableApps.Settings.AllAppsSpecialCommand
  - Plugin_PortableApps.Settings.BlackList
  - Plugin_PortableApps.Settings.FuzzySearchThreshold
  - Plugin_PortableApps.Settings.PortableAppsDirectory
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: Settings
  fullName: Plugin_PortableApps.Settings
  type: Class
  source:
    remote:
      path: Plugin_PortableApps/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: Settings
    path: ../Plugin_PortableApps/Settings.cs
    startLine: 5
  assemblies:
  - Plugin_PortableApps
  namespace: Plugin_PortableApps
  syntax:
    content: public class Settings
    content.vb: Public Class Settings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Plugin_PortableApps.Settings.PortableAppsDirectory
  commentId: P:Plugin_PortableApps.Settings.PortableAppsDirectory
  id: PortableAppsDirectory
  parent: Plugin_PortableApps.Settings
  langs:
  - csharp
  - vb
  name: PortableAppsDirectory
  nameWithType: Settings.PortableAppsDirectory
  fullName: Plugin_PortableApps.Settings.PortableAppsDirectory
  type: Property
  source:
    remote:
      path: Plugin_PortableApps/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: PortableAppsDirectory
    path: ../Plugin_PortableApps/Settings.cs
    startLine: 7
  assemblies:
  - Plugin_PortableApps
  namespace: Plugin_PortableApps
  syntax:
    content: public string PortableAppsDirectory { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property PortableAppsDirectory As String
  overload: Plugin_PortableApps.Settings.PortableAppsDirectory*
- uid: Plugin_PortableApps.Settings.AllAppsSpecialCommand
  commentId: P:Plugin_PortableApps.Settings.AllAppsSpecialCommand
  id: AllAppsSpecialCommand
  parent: Plugin_PortableApps.Settings
  langs:
  - csharp
  - vb
  name: AllAppsSpecialCommand
  nameWithType: Settings.AllAppsSpecialCommand
  fullName: Plugin_PortableApps.Settings.AllAppsSpecialCommand
  type: Property
  source:
    remote:
      path: Plugin_PortableApps/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: AllAppsSpecialCommand
    path: ../Plugin_PortableApps/Settings.cs
    startLine: 8
  assemblies:
  - Plugin_PortableApps
  namespace: Plugin_PortableApps
  syntax:
    content: public string AllAppsSpecialCommand { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property AllAppsSpecialCommand As String
  overload: Plugin_PortableApps.Settings.AllAppsSpecialCommand*
- uid: Plugin_PortableApps.Settings.BlackList
  commentId: P:Plugin_PortableApps.Settings.BlackList
  id: BlackList
  parent: Plugin_PortableApps.Settings
  langs:
  - csharp
  - vb
  name: BlackList
  nameWithType: Settings.BlackList
  fullName: Plugin_PortableApps.Settings.BlackList
  type: Property
  source:
    remote:
      path: Plugin_PortableApps/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: BlackList
    path: ../Plugin_PortableApps/Settings.cs
    startLine: 9
  assemblies:
  - Plugin_PortableApps
  namespace: Plugin_PortableApps
  syntax:
    content: public List<string> BlackList { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public Property BlackList As List(Of String)
  overload: Plugin_PortableApps.Settings.BlackList*
- uid: Plugin_PortableApps.Settings.FuzzySearchThreshold
  commentId: P:Plugin_PortableApps.Settings.FuzzySearchThreshold
  id: FuzzySearchThreshold
  parent: Plugin_PortableApps.Settings
  langs:
  - csharp
  - vb
  name: FuzzySearchThreshold
  nameWithType: Settings.FuzzySearchThreshold
  fullName: Plugin_PortableApps.Settings.FuzzySearchThreshold
  type: Property
  source:
    remote:
      path: Plugin_PortableApps/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: FuzzySearchThreshold
    path: ../Plugin_PortableApps/Settings.cs
    startLine: 10
  assemblies:
  - Plugin_PortableApps
  namespace: Plugin_PortableApps
  syntax:
    content: public int FuzzySearchThreshold { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property FuzzySearchThreshold As Integer
  overload: Plugin_PortableApps.Settings.FuzzySearchThreshold*
references:
- uid: Plugin_PortableApps
  commentId: N:Plugin_PortableApps
  href: Plugin_PortableApps.html
  name: Plugin_PortableApps
  nameWithType: Plugin_PortableApps
  fullName: Plugin_PortableApps
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Plugin_PortableApps.Settings.PortableAppsDirectory*
  commentId: Overload:Plugin_PortableApps.Settings.PortableAppsDirectory
  href: Plugin_PortableApps.Settings.html#Plugin_PortableApps_Settings_PortableAppsDirectory
  name: PortableAppsDirectory
  nameWithType: Settings.PortableAppsDirectory
  fullName: Plugin_PortableApps.Settings.PortableAppsDirectory
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Plugin_PortableApps.Settings.AllAppsSpecialCommand*
  commentId: Overload:Plugin_PortableApps.Settings.AllAppsSpecialCommand
  href: Plugin_PortableApps.Settings.html#Plugin_PortableApps_Settings_AllAppsSpecialCommand
  name: AllAppsSpecialCommand
  nameWithType: Settings.AllAppsSpecialCommand
  fullName: Plugin_PortableApps.Settings.AllAppsSpecialCommand
- uid: Plugin_PortableApps.Settings.BlackList*
  commentId: Overload:Plugin_PortableApps.Settings.BlackList
  href: Plugin_PortableApps.Settings.html#Plugin_PortableApps_Settings_BlackList
  name: BlackList
  nameWithType: Settings.BlackList
  fullName: Plugin_PortableApps.Settings.BlackList
- uid: System.Collections.Generic.List{System.String}
  commentId: T:System.Collections.Generic.List{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<string>
  nameWithType: List<string>
  fullName: System.Collections.Generic.List<string>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Plugin_PortableApps.Settings.FuzzySearchThreshold*
  commentId: Overload:Plugin_PortableApps.Settings.FuzzySearchThreshold
  href: Plugin_PortableApps.Settings.html#Plugin_PortableApps_Settings_FuzzySearchThreshold
  name: FuzzySearchThreshold
  nameWithType: Settings.FuzzySearchThreshold
  fullName: Plugin_PortableApps.Settings.FuzzySearchThreshold
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
