### YamlMime:ManagedReference
items:
- uid: Quokka.Settings.StyleSettings
  commentId: T:Quokka.Settings.StyleSettings
  id: StyleSettings
  parent: Quokka.Settings
  children:
  - Quokka.Settings.StyleSettings.AppWindow
  - Quokka.Settings.StyleSettings.ResultsList
  - Quokka.Settings.StyleSettings.SearchBar
  langs:
  - csharp
  - vb
  name: StyleSettings
  nameWithType: StyleSettings
  fullName: Quokka.Settings.StyleSettings
  type: Class
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: StyleSettings
    path: ../Quokka/Settings/Settings.cs
    startLine: 134
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public class StyleSettings
    content.vb: Public Class StyleSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quokka.Settings.StyleSettings.AppWindow
  commentId: P:Quokka.Settings.StyleSettings.AppWindow
  id: AppWindow
  parent: Quokka.Settings.StyleSettings
  langs:
  - csharp
  - vb
  name: AppWindow
  nameWithType: StyleSettings.AppWindow
  fullName: Quokka.Settings.StyleSettings.AppWindow
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: AppWindow
    path: ../Quokka/Settings/Settings.cs
    startLine: 136
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public AppWindow AppWindow { get; set; }
    parameters: []
    return:
      type: Quokka.Settings.AppWindow
    content.vb: Public Property AppWindow As AppWindow
  overload: Quokka.Settings.StyleSettings.AppWindow*
- uid: Quokka.Settings.StyleSettings.SearchBar
  commentId: P:Quokka.Settings.StyleSettings.SearchBar
  id: SearchBar
  parent: Quokka.Settings.StyleSettings
  langs:
  - csharp
  - vb
  name: SearchBar
  nameWithType: StyleSettings.SearchBar
  fullName: Quokka.Settings.StyleSettings.SearchBar
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: SearchBar
    path: ../Quokka/Settings/Settings.cs
    startLine: 137
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public SearchBar SearchBar { get; set; }
    parameters: []
    return:
      type: Quokka.Settings.SearchBar
    content.vb: Public Property SearchBar As SearchBar
  overload: Quokka.Settings.StyleSettings.SearchBar*
- uid: Quokka.Settings.StyleSettings.ResultsList
  commentId: P:Quokka.Settings.StyleSettings.ResultsList
  id: ResultsList
  parent: Quokka.Settings.StyleSettings
  langs:
  - csharp
  - vb
  name: ResultsList
  nameWithType: StyleSettings.ResultsList
  fullName: Quokka.Settings.StyleSettings.ResultsList
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ResultsList
    path: ../Quokka/Settings/Settings.cs
    startLine: 138
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public ResultsList ResultsList { get; set; }
    parameters: []
    return:
      type: Quokka.Settings.ResultsList
    content.vb: Public Property ResultsList As ResultsList
  overload: Quokka.Settings.StyleSettings.ResultsList*
references:
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  href: Quokka.html
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  spec.csharp:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
  spec.vb:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quokka.Settings.StyleSettings.AppWindow*
  commentId: Overload:Quokka.Settings.StyleSettings.AppWindow
  href: Quokka.Settings.StyleSettings.html#Quokka_Settings_StyleSettings_AppWindow
  name: AppWindow
  nameWithType: StyleSettings.AppWindow
  fullName: Quokka.Settings.StyleSettings.AppWindow
- uid: Quokka.Settings.AppWindow
  commentId: T:Quokka.Settings.AppWindow
  parent: Quokka.Settings
  href: Quokka.Settings.AppWindow.html
  name: AppWindow
  nameWithType: AppWindow
  fullName: Quokka.Settings.AppWindow
- uid: Quokka.Settings.StyleSettings.SearchBar*
  commentId: Overload:Quokka.Settings.StyleSettings.SearchBar
  href: Quokka.Settings.StyleSettings.html#Quokka_Settings_StyleSettings_SearchBar
  name: SearchBar
  nameWithType: StyleSettings.SearchBar
  fullName: Quokka.Settings.StyleSettings.SearchBar
- uid: Quokka.Settings.SearchBar
  commentId: T:Quokka.Settings.SearchBar
  parent: Quokka.Settings
  href: Quokka.Settings.SearchBar.html
  name: SearchBar
  nameWithType: SearchBar
  fullName: Quokka.Settings.SearchBar
- uid: Quokka.Settings.StyleSettings.ResultsList*
  commentId: Overload:Quokka.Settings.StyleSettings.ResultsList
  href: Quokka.Settings.StyleSettings.html#Quokka_Settings_StyleSettings_ResultsList
  name: ResultsList
  nameWithType: StyleSettings.ResultsList
  fullName: Quokka.Settings.StyleSettings.ResultsList
- uid: Quokka.Settings.ResultsList
  commentId: T:Quokka.Settings.ResultsList
  parent: Quokka.Settings
  href: Quokka.Settings.ResultsList.html
  name: ResultsList
  nameWithType: ResultsList
  fullName: Quokka.Settings.ResultsList
