### YamlMime:ManagedReference
items:
- uid: Quokka.Settings.AppWindow
  commentId: T:Quokka.Settings.AppWindow
  id: AppWindow
  parent: Quokka.Settings
  children:
  - Quokka.Settings.AppWindow.WindowBorderColor
  - Quokka.Settings.AppWindow.WindowBorderThickness
  - Quokka.Settings.AppWindow.WindowColor
  - Quokka.Settings.AppWindow.WindowPadding
  - Quokka.Settings.AppWindow.WindowRounding
  - Quokka.Settings.AppWindow.WindowTopMargin
  - Quokka.Settings.AppWindow.WindowWidth
  langs:
  - csharp
  - vb
  name: AppWindow
  nameWithType: AppWindow
  fullName: Quokka.Settings.AppWindow
  type: Class
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: AppWindow
    path: ../Quokka/Settings/Settings.cs
    startLine: 8
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public class AppWindow
    content.vb: Public Class AppWindow
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quokka.Settings.AppWindow.WindowTopMargin
  commentId: P:Quokka.Settings.AppWindow.WindowTopMargin
  id: WindowTopMargin
  parent: Quokka.Settings.AppWindow
  langs:
  - csharp
  - vb
  name: WindowTopMargin
  nameWithType: AppWindow.WindowTopMargin
  fullName: Quokka.Settings.AppWindow.WindowTopMargin
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: WindowTopMargin
    path: ../Quokka/Settings/Settings.cs
    startLine: 10
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string WindowTopMargin { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WindowTopMargin As String
  overload: Quokka.Settings.AppWindow.WindowTopMargin*
- uid: Quokka.Settings.AppWindow.WindowWidth
  commentId: P:Quokka.Settings.AppWindow.WindowWidth
  id: WindowWidth
  parent: Quokka.Settings.AppWindow
  langs:
  - csharp
  - vb
  name: WindowWidth
  nameWithType: AppWindow.WindowWidth
  fullName: Quokka.Settings.AppWindow.WindowWidth
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: WindowWidth
    path: ../Quokka/Settings/Settings.cs
    startLine: 11
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string WindowWidth { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WindowWidth As String
  overload: Quokka.Settings.AppWindow.WindowWidth*
- uid: Quokka.Settings.AppWindow.WindowColor
  commentId: P:Quokka.Settings.AppWindow.WindowColor
  id: WindowColor
  parent: Quokka.Settings.AppWindow
  langs:
  - csharp
  - vb
  name: WindowColor
  nameWithType: AppWindow.WindowColor
  fullName: Quokka.Settings.AppWindow.WindowColor
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: WindowColor
    path: ../Quokka/Settings/Settings.cs
    startLine: 12
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string WindowColor { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WindowColor As String
  overload: Quokka.Settings.AppWindow.WindowColor*
- uid: Quokka.Settings.AppWindow.WindowBorderColor
  commentId: P:Quokka.Settings.AppWindow.WindowBorderColor
  id: WindowBorderColor
  parent: Quokka.Settings.AppWindow
  langs:
  - csharp
  - vb
  name: WindowBorderColor
  nameWithType: AppWindow.WindowBorderColor
  fullName: Quokka.Settings.AppWindow.WindowBorderColor
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: WindowBorderColor
    path: ../Quokka/Settings/Settings.cs
    startLine: 13
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string WindowBorderColor { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WindowBorderColor As String
  overload: Quokka.Settings.AppWindow.WindowBorderColor*
- uid: Quokka.Settings.AppWindow.WindowBorderThickness
  commentId: P:Quokka.Settings.AppWindow.WindowBorderThickness
  id: WindowBorderThickness
  parent: Quokka.Settings.AppWindow
  langs:
  - csharp
  - vb
  name: WindowBorderThickness
  nameWithType: AppWindow.WindowBorderThickness
  fullName: Quokka.Settings.AppWindow.WindowBorderThickness
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: WindowBorderThickness
    path: ../Quokka/Settings/Settings.cs
    startLine: 14
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string WindowBorderThickness { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WindowBorderThickness As String
  overload: Quokka.Settings.AppWindow.WindowBorderThickness*
- uid: Quokka.Settings.AppWindow.WindowRounding
  commentId: P:Quokka.Settings.AppWindow.WindowRounding
  id: WindowRounding
  parent: Quokka.Settings.AppWindow
  langs:
  - csharp
  - vb
  name: WindowRounding
  nameWithType: AppWindow.WindowRounding
  fullName: Quokka.Settings.AppWindow.WindowRounding
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: WindowRounding
    path: ../Quokka/Settings/Settings.cs
    startLine: 15
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string WindowRounding { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WindowRounding As String
  overload: Quokka.Settings.AppWindow.WindowRounding*
- uid: Quokka.Settings.AppWindow.WindowPadding
  commentId: P:Quokka.Settings.AppWindow.WindowPadding
  id: WindowPadding
  parent: Quokka.Settings.AppWindow
  langs:
  - csharp
  - vb
  name: WindowPadding
  nameWithType: AppWindow.WindowPadding
  fullName: Quokka.Settings.AppWindow.WindowPadding
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: WindowPadding
    path: ../Quokka/Settings/Settings.cs
    startLine: 16
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string WindowPadding { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WindowPadding As String
  overload: Quokka.Settings.AppWindow.WindowPadding*
references:
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  href: Quokka.html
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  spec.csharp:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
  spec.vb:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quokka.Settings.AppWindow.WindowTopMargin*
  commentId: Overload:Quokka.Settings.AppWindow.WindowTopMargin
  href: Quokka.Settings.AppWindow.html#Quokka_Settings_AppWindow_WindowTopMargin
  name: WindowTopMargin
  nameWithType: AppWindow.WindowTopMargin
  fullName: Quokka.Settings.AppWindow.WindowTopMargin
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Quokka.Settings.AppWindow.WindowWidth*
  commentId: Overload:Quokka.Settings.AppWindow.WindowWidth
  href: Quokka.Settings.AppWindow.html#Quokka_Settings_AppWindow_WindowWidth
  name: WindowWidth
  nameWithType: AppWindow.WindowWidth
  fullName: Quokka.Settings.AppWindow.WindowWidth
- uid: Quokka.Settings.AppWindow.WindowColor*
  commentId: Overload:Quokka.Settings.AppWindow.WindowColor
  href: Quokka.Settings.AppWindow.html#Quokka_Settings_AppWindow_WindowColor
  name: WindowColor
  nameWithType: AppWindow.WindowColor
  fullName: Quokka.Settings.AppWindow.WindowColor
- uid: Quokka.Settings.AppWindow.WindowBorderColor*
  commentId: Overload:Quokka.Settings.AppWindow.WindowBorderColor
  href: Quokka.Settings.AppWindow.html#Quokka_Settings_AppWindow_WindowBorderColor
  name: WindowBorderColor
  nameWithType: AppWindow.WindowBorderColor
  fullName: Quokka.Settings.AppWindow.WindowBorderColor
- uid: Quokka.Settings.AppWindow.WindowBorderThickness*
  commentId: Overload:Quokka.Settings.AppWindow.WindowBorderThickness
  href: Quokka.Settings.AppWindow.html#Quokka_Settings_AppWindow_WindowBorderThickness
  name: WindowBorderThickness
  nameWithType: AppWindow.WindowBorderThickness
  fullName: Quokka.Settings.AppWindow.WindowBorderThickness
- uid: Quokka.Settings.AppWindow.WindowRounding*
  commentId: Overload:Quokka.Settings.AppWindow.WindowRounding
  href: Quokka.Settings.AppWindow.html#Quokka_Settings_AppWindow_WindowRounding
  name: WindowRounding
  nameWithType: AppWindow.WindowRounding
  fullName: Quokka.Settings.AppWindow.WindowRounding
- uid: Quokka.Settings.AppWindow.WindowPadding*
  commentId: Overload:Quokka.Settings.AppWindow.WindowPadding
  href: Quokka.Settings.AppWindow.html#Quokka_Settings_AppWindow_WindowPadding
  name: WindowPadding
  nameWithType: AppWindow.WindowPadding
  fullName: Quokka.Settings.AppWindow.WindowPadding
