### YamlMime:ManagedReference
items:
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  id: Quokka.Settings
  children:
  - Quokka.Settings.AppWindow
  - Quokka.Settings.Container
  - Quokka.Settings.ContextPane
  - Quokka.Settings.Details
  - Quokka.Settings.EntryField
  - Quokka.Settings.GeneralSettings
  - Quokka.Settings.List
  - Quokka.Settings.ListItems
  - Quokka.Settings.ResultsList
  - Quokka.Settings.SearchBar
  - Quokka.Settings.SettingParsers
  - Quokka.Settings.Settings
  - Quokka.Settings.StyleSettings
  langs:
  - csharp
  - vb
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  type: Namespace
  assemblies:
  - Quokka
references:
- uid: Quokka.Settings.SettingParsers
  commentId: T:Quokka.Settings.SettingParsers
  href: Quokka.Settings.SettingParsers.html
  name: SettingParsers
  nameWithType: SettingParsers
  fullName: Quokka.Settings.SettingParsers
- uid: Quokka.Settings.AppWindow
  commentId: T:Quokka.Settings.AppWindow
  parent: Quokka.Settings
  href: Quokka.Settings.AppWindow.html
  name: AppWindow
  nameWithType: AppWindow
  fullName: Quokka.Settings.AppWindow
- uid: Quokka.Settings.Container
  commentId: T:Quokka.Settings.Container
  parent: Quokka.Settings
  href: Quokka.Settings.Container.html
  name: Container
  nameWithType: Container
  fullName: Quokka.Settings.Container
- uid: Quokka.Settings.ContextPane
  commentId: T:Quokka.Settings.ContextPane
  parent: Quokka.Settings
  href: Quokka.Settings.ContextPane.html
  name: ContextPane
  nameWithType: ContextPane
  fullName: Quokka.Settings.ContextPane
- uid: Quokka.Settings.Details
  commentId: T:Quokka.Settings.Details
  parent: Quokka.Settings
  href: Quokka.Settings.Details.html
  name: Details
  nameWithType: Details
  fullName: Quokka.Settings.Details
- uid: Quokka.Settings.EntryField
  commentId: T:Quokka.Settings.EntryField
  parent: Quokka.Settings
  href: Quokka.Settings.EntryField.html
  name: EntryField
  nameWithType: EntryField
  fullName: Quokka.Settings.EntryField
- uid: Quokka.Settings.GeneralSettings
  commentId: T:Quokka.Settings.GeneralSettings
  parent: Quokka.Settings
  href: Quokka.Settings.GeneralSettings.html
  name: GeneralSettings
  nameWithType: GeneralSettings
  fullName: Quokka.Settings.GeneralSettings
- uid: Quokka.Settings.List
  commentId: T:Quokka.Settings.List
  parent: Quokka.Settings
  href: Quokka.Settings.List.html
  name: List
  nameWithType: List
  fullName: Quokka.Settings.List
- uid: Quokka.Settings.ListItems
  commentId: T:Quokka.Settings.ListItems
  parent: Quokka.Settings
  href: Quokka.Settings.ListItems.html
  name: ListItems
  nameWithType: ListItems
  fullName: Quokka.Settings.ListItems
- uid: Quokka.Settings.ResultsList
  commentId: T:Quokka.Settings.ResultsList
  parent: Quokka.Settings
  href: Quokka.Settings.ResultsList.html
  name: ResultsList
  nameWithType: ResultsList
  fullName: Quokka.Settings.ResultsList
- uid: Quokka.Settings.Settings
  commentId: T:Quokka.Settings.Settings
  parent: Quokka.Settings
  href: Quokka.Settings.Settings.html
  name: Settings
  nameWithType: Settings
  fullName: Quokka.Settings.Settings
- uid: Quokka.Settings.SearchBar
  commentId: T:Quokka.Settings.SearchBar
  parent: Quokka.Settings
  href: Quokka.Settings.SearchBar.html
  name: SearchBar
  nameWithType: SearchBar
  fullName: Quokka.Settings.SearchBar
- uid: Quokka.Settings.StyleSettings
  commentId: T:Quokka.Settings.StyleSettings
  parent: Quokka.Settings
  href: Quokka.Settings.StyleSettings.html
  name: StyleSettings
  nameWithType: StyleSettings
  fullName: Quokka.Settings.StyleSettings
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  href: Quokka.html
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  spec.csharp:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
  spec.vb:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
