### YamlMime:ManagedReference
items:
- uid: Quokka.Settings.Container
  commentId: T:Quokka.Settings.Container
  id: Container
  parent: Quokka.Settings
  children:
  - Quokka.Settings.Container.ListContainerBorderColor
  - Quokka.Settings.Container.ListContainerBorderThickness
  - Quokka.Settings.Container.ListContainerColor
  - Quokka.Settings.Container.ListContainerMargin
  - Quokka.Settings.Container.ListContainerMaxHeight
  - Quokka.Settings.Container.ListContainerMinHeight
  - Quokka.Settings.Container.ListContainerRounding
  langs:
  - csharp
  - vb
  name: Container
  nameWithType: Container
  fullName: Quokka.Settings.Container
  type: Class
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: Container
    path: ../Quokka/Settings/Settings.cs
    startLine: 19
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public class Container
    content.vb: Public Class Container
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quokka.Settings.Container.ListContainerMargin
  commentId: P:Quokka.Settings.Container.ListContainerMargin
  id: ListContainerMargin
  parent: Quokka.Settings.Container
  langs:
  - csharp
  - vb
  name: ListContainerMargin
  nameWithType: Container.ListContainerMargin
  fullName: Quokka.Settings.Container.ListContainerMargin
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListContainerMargin
    path: ../Quokka/Settings/Settings.cs
    startLine: 21
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ListContainerMargin { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ListContainerMargin As String
  overload: Quokka.Settings.Container.ListContainerMargin*
- uid: Quokka.Settings.Container.ListContainerBorderColor
  commentId: P:Quokka.Settings.Container.ListContainerBorderColor
  id: ListContainerBorderColor
  parent: Quokka.Settings.Container
  langs:
  - csharp
  - vb
  name: ListContainerBorderColor
  nameWithType: Container.ListContainerBorderColor
  fullName: Quokka.Settings.Container.ListContainerBorderColor
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListContainerBorderColor
    path: ../Quokka/Settings/Settings.cs
    startLine: 22
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ListContainerBorderColor { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ListContainerBorderColor As String
  overload: Quokka.Settings.Container.ListContainerBorderColor*
- uid: Quokka.Settings.Container.ListContainerBorderThickness
  commentId: P:Quokka.Settings.Container.ListContainerBorderThickness
  id: ListContainerBorderThickness
  parent: Quokka.Settings.Container
  langs:
  - csharp
  - vb
  name: ListContainerBorderThickness
  nameWithType: Container.ListContainerBorderThickness
  fullName: Quokka.Settings.Container.ListContainerBorderThickness
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListContainerBorderThickness
    path: ../Quokka/Settings/Settings.cs
    startLine: 23
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ListContainerBorderThickness { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ListContainerBorderThickness As String
  overload: Quokka.Settings.Container.ListContainerBorderThickness*
- uid: Quokka.Settings.Container.ListContainerRounding
  commentId: P:Quokka.Settings.Container.ListContainerRounding
  id: ListContainerRounding
  parent: Quokka.Settings.Container
  langs:
  - csharp
  - vb
  name: ListContainerRounding
  nameWithType: Container.ListContainerRounding
  fullName: Quokka.Settings.Container.ListContainerRounding
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListContainerRounding
    path: ../Quokka/Settings/Settings.cs
    startLine: 24
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ListContainerRounding { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ListContainerRounding As String
  overload: Quokka.Settings.Container.ListContainerRounding*
- uid: Quokka.Settings.Container.ListContainerColor
  commentId: P:Quokka.Settings.Container.ListContainerColor
  id: ListContainerColor
  parent: Quokka.Settings.Container
  langs:
  - csharp
  - vb
  name: ListContainerColor
  nameWithType: Container.ListContainerColor
  fullName: Quokka.Settings.Container.ListContainerColor
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListContainerColor
    path: ../Quokka/Settings/Settings.cs
    startLine: 25
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ListContainerColor { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ListContainerColor As String
  overload: Quokka.Settings.Container.ListContainerColor*
- uid: Quokka.Settings.Container.ListContainerMinHeight
  commentId: P:Quokka.Settings.Container.ListContainerMinHeight
  id: ListContainerMinHeight
  parent: Quokka.Settings.Container
  langs:
  - csharp
  - vb
  name: ListContainerMinHeight
  nameWithType: Container.ListContainerMinHeight
  fullName: Quokka.Settings.Container.ListContainerMinHeight
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListContainerMinHeight
    path: ../Quokka/Settings/Settings.cs
    startLine: 26
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ListContainerMinHeight { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ListContainerMinHeight As String
  overload: Quokka.Settings.Container.ListContainerMinHeight*
- uid: Quokka.Settings.Container.ListContainerMaxHeight
  commentId: P:Quokka.Settings.Container.ListContainerMaxHeight
  id: ListContainerMaxHeight
  parent: Quokka.Settings.Container
  langs:
  - csharp
  - vb
  name: ListContainerMaxHeight
  nameWithType: Container.ListContainerMaxHeight
  fullName: Quokka.Settings.Container.ListContainerMaxHeight
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListContainerMaxHeight
    path: ../Quokka/Settings/Settings.cs
    startLine: 27
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ListContainerMaxHeight { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ListContainerMaxHeight As String
  overload: Quokka.Settings.Container.ListContainerMaxHeight*
references:
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  href: Quokka.html
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  spec.csharp:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
  spec.vb:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quokka.Settings.Container.ListContainerMargin*
  commentId: Overload:Quokka.Settings.Container.ListContainerMargin
  href: Quokka.Settings.Container.html#Quokka_Settings_Container_ListContainerMargin
  name: ListContainerMargin
  nameWithType: Container.ListContainerMargin
  fullName: Quokka.Settings.Container.ListContainerMargin
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Quokka.Settings.Container.ListContainerBorderColor*
  commentId: Overload:Quokka.Settings.Container.ListContainerBorderColor
  href: Quokka.Settings.Container.html#Quokka_Settings_Container_ListContainerBorderColor
  name: ListContainerBorderColor
  nameWithType: Container.ListContainerBorderColor
  fullName: Quokka.Settings.Container.ListContainerBorderColor
- uid: Quokka.Settings.Container.ListContainerBorderThickness*
  commentId: Overload:Quokka.Settings.Container.ListContainerBorderThickness
  href: Quokka.Settings.Container.html#Quokka_Settings_Container_ListContainerBorderThickness
  name: ListContainerBorderThickness
  nameWithType: Container.ListContainerBorderThickness
  fullName: Quokka.Settings.Container.ListContainerBorderThickness
- uid: Quokka.Settings.Container.ListContainerRounding*
  commentId: Overload:Quokka.Settings.Container.ListContainerRounding
  href: Quokka.Settings.Container.html#Quokka_Settings_Container_ListContainerRounding
  name: ListContainerRounding
  nameWithType: Container.ListContainerRounding
  fullName: Quokka.Settings.Container.ListContainerRounding
- uid: Quokka.Settings.Container.ListContainerColor*
  commentId: Overload:Quokka.Settings.Container.ListContainerColor
  href: Quokka.Settings.Container.html#Quokka_Settings_Container_ListContainerColor
  name: ListContainerColor
  nameWithType: Container.ListContainerColor
  fullName: Quokka.Settings.Container.ListContainerColor
- uid: Quokka.Settings.Container.ListContainerMinHeight*
  commentId: Overload:Quokka.Settings.Container.ListContainerMinHeight
  href: Quokka.Settings.Container.html#Quokka_Settings_Container_ListContainerMinHeight
  name: ListContainerMinHeight
  nameWithType: Container.ListContainerMinHeight
  fullName: Quokka.Settings.Container.ListContainerMinHeight
- uid: Quokka.Settings.Container.ListContainerMaxHeight*
  commentId: Overload:Quokka.Settings.Container.ListContainerMaxHeight
  href: Quokka.Settings.Container.html#Quokka_Settings_Container_ListContainerMaxHeight
  name: ListContainerMaxHeight
  nameWithType: Container.ListContainerMaxHeight
  fullName: Quokka.Settings.Container.ListContainerMaxHeight
