### YamlMime:ManagedReference
items:
- uid: Quokka.Settings.ResultsList
  commentId: T:Quokka.Settings.ResultsList
  id: ResultsList
  parent: Quokka.Settings
  children:
  - Quokka.Settings.ResultsList.Container
  - Quokka.Settings.ResultsList.List
  - Quokka.Settings.ResultsList.ListItems
  langs:
  - csharp
  - vb
  name: ResultsList
  nameWithType: ResultsList
  fullName: Quokka.Settings.ResultsList
  type: Class
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ResultsList
    path: ../Quokka/Settings/Settings.cs
    startLine: 109
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public class ResultsList
    content.vb: Public Class ResultsList
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quokka.Settings.ResultsList.Container
  commentId: P:Quokka.Settings.ResultsList.Container
  id: Container
  parent: Quokka.Settings.ResultsList
  langs:
  - csharp
  - vb
  name: Container
  nameWithType: ResultsList.Container
  fullName: Quokka.Settings.ResultsList.Container
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: Container
    path: ../Quokka/Settings/Settings.cs
    startLine: 111
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public Container Container { get; set; }
    parameters: []
    return:
      type: Quokka.Settings.Container
    content.vb: Public Property Container As Container
  overload: Quokka.Settings.ResultsList.Container*
- uid: Quokka.Settings.ResultsList.List
  commentId: P:Quokka.Settings.ResultsList.List
  id: List
  parent: Quokka.Settings.ResultsList
  langs:
  - csharp
  - vb
  name: List
  nameWithType: ResultsList.List
  fullName: Quokka.Settings.ResultsList.List
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: List
    path: ../Quokka/Settings/Settings.cs
    startLine: 112
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public List List { get; set; }
    parameters: []
    return:
      type: Quokka.Settings.List
    content.vb: Public Property List As List
  overload: Quokka.Settings.ResultsList.List*
- uid: Quokka.Settings.ResultsList.ListItems
  commentId: P:Quokka.Settings.ResultsList.ListItems
  id: ListItems
  parent: Quokka.Settings.ResultsList
  langs:
  - csharp
  - vb
  name: ListItems
  nameWithType: ResultsList.ListItems
  fullName: Quokka.Settings.ResultsList.ListItems
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListItems
    path: ../Quokka/Settings/Settings.cs
    startLine: 113
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public ListItems ListItems { get; set; }
    parameters: []
    return:
      type: Quokka.Settings.ListItems
    content.vb: Public Property ListItems As ListItems
  overload: Quokka.Settings.ResultsList.ListItems*
references:
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  href: Quokka.html
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  spec.csharp:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
  spec.vb:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quokka.Settings.ResultsList.Container*
  commentId: Overload:Quokka.Settings.ResultsList.Container
  href: Quokka.Settings.ResultsList.html#Quokka_Settings_ResultsList_Container
  name: Container
  nameWithType: ResultsList.Container
  fullName: Quokka.Settings.ResultsList.Container
- uid: Quokka.Settings.Container
  commentId: T:Quokka.Settings.Container
  parent: Quokka.Settings
  href: Quokka.Settings.Container.html
  name: Container
  nameWithType: Container
  fullName: Quokka.Settings.Container
- uid: Quokka.Settings.ResultsList.List*
  commentId: Overload:Quokka.Settings.ResultsList.List
  href: Quokka.Settings.ResultsList.html#Quokka_Settings_ResultsList_List
  name: List
  nameWithType: ResultsList.List
  fullName: Quokka.Settings.ResultsList.List
- uid: Quokka.Settings.List
  commentId: T:Quokka.Settings.List
  parent: Quokka.Settings
  href: Quokka.Settings.List.html
  name: List
  nameWithType: List
  fullName: Quokka.Settings.List
- uid: Quokka.Settings.ResultsList.ListItems*
  commentId: Overload:Quokka.Settings.ResultsList.ListItems
  href: Quokka.Settings.ResultsList.html#Quokka_Settings_ResultsList_ListItems
  name: ListItems
  nameWithType: ResultsList.ListItems
  fullName: Quokka.Settings.ResultsList.ListItems
- uid: Quokka.Settings.ListItems
  commentId: T:Quokka.Settings.ListItems
  parent: Quokka.Settings
  href: Quokka.Settings.ListItems.html
  name: ListItems
  nameWithType: ListItems
  fullName: Quokka.Settings.ListItems
