### YamlMime:ManagedReference
items:
- uid: Quokka.Settings.GeneralSettings
  commentId: T:Quokka.Settings.GeneralSettings
  id: GeneralSettings
  parent: Quokka.Settings
  children:
  - Quokka.Settings.GeneralSettings.IgnoreMaxResultsFlag
  - Quokka.Settings.GeneralSettings.MaxResults
  - Quokka.Settings.GeneralSettings.WindowHotKey
  langs:
  - csharp
  - vb
  name: GeneralSettings
  nameWithType: GeneralSettings
  fullName: Quokka.Settings.GeneralSettings
  type: Class
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: GeneralSettings
    path: ../Quokka/Settings/Settings.cs
    startLine: 69
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public class GeneralSettings
    content.vb: Public Class GeneralSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quokka.Settings.GeneralSettings.WindowHotKey
  commentId: P:Quokka.Settings.GeneralSettings.WindowHotKey
  id: WindowHotKey
  parent: Quokka.Settings.GeneralSettings
  langs:
  - csharp
  - vb
  name: WindowHotKey
  nameWithType: GeneralSettings.WindowHotKey
  fullName: Quokka.Settings.GeneralSettings.WindowHotKey
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: WindowHotKey
    path: ../Quokka/Settings/Settings.cs
    startLine: 71
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string WindowHotKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WindowHotKey As String
  overload: Quokka.Settings.GeneralSettings.WindowHotKey*
- uid: Quokka.Settings.GeneralSettings.MaxResults
  commentId: P:Quokka.Settings.GeneralSettings.MaxResults
  id: MaxResults
  parent: Quokka.Settings.GeneralSettings
  langs:
  - csharp
  - vb
  name: MaxResults
  nameWithType: GeneralSettings.MaxResults
  fullName: Quokka.Settings.GeneralSettings.MaxResults
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: MaxResults
    path: ../Quokka/Settings/Settings.cs
    startLine: 72
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string MaxResults { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property MaxResults As String
  overload: Quokka.Settings.GeneralSettings.MaxResults*
- uid: Quokka.Settings.GeneralSettings.IgnoreMaxResultsFlag
  commentId: P:Quokka.Settings.GeneralSettings.IgnoreMaxResultsFlag
  id: IgnoreMaxResultsFlag
  parent: Quokka.Settings.GeneralSettings
  langs:
  - csharp
  - vb
  name: IgnoreMaxResultsFlag
  nameWithType: GeneralSettings.IgnoreMaxResultsFlag
  fullName: Quokka.Settings.GeneralSettings.IgnoreMaxResultsFlag
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: IgnoreMaxResultsFlag
    path: ../Quokka/Settings/Settings.cs
    startLine: 73
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string IgnoreMaxResultsFlag { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property IgnoreMaxResultsFlag As String
  overload: Quokka.Settings.GeneralSettings.IgnoreMaxResultsFlag*
references:
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  href: Quokka.html
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  spec.csharp:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
  spec.vb:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quokka.Settings.GeneralSettings.WindowHotKey*
  commentId: Overload:Quokka.Settings.GeneralSettings.WindowHotKey
  href: Quokka.Settings.GeneralSettings.html#Quokka_Settings_GeneralSettings_WindowHotKey
  name: WindowHotKey
  nameWithType: GeneralSettings.WindowHotKey
  fullName: Quokka.Settings.GeneralSettings.WindowHotKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Quokka.Settings.GeneralSettings.MaxResults*
  commentId: Overload:Quokka.Settings.GeneralSettings.MaxResults
  href: Quokka.Settings.GeneralSettings.html#Quokka_Settings_GeneralSettings_MaxResults
  name: MaxResults
  nameWithType: GeneralSettings.MaxResults
  fullName: Quokka.Settings.GeneralSettings.MaxResults
- uid: Quokka.Settings.GeneralSettings.IgnoreMaxResultsFlag*
  commentId: Overload:Quokka.Settings.GeneralSettings.IgnoreMaxResultsFlag
  href: Quokka.Settings.GeneralSettings.html#Quokka_Settings_GeneralSettings_IgnoreMaxResultsFlag
  name: IgnoreMaxResultsFlag
  nameWithType: GeneralSettings.IgnoreMaxResultsFlag
  fullName: Quokka.Settings.GeneralSettings.IgnoreMaxResultsFlag
