### YamlMime:ManagedReference
items:
- uid: Quokka.Settings.List
  commentId: T:Quokka.Settings.List
  id: List
  parent: Quokka.Settings
  children:
  - Quokka.Settings.List.ButtonContentMargin
  - Quokka.Settings.List.ContentHorizontalAlignment
  - Quokka.Settings.List.ListItems
  - Quokka.Settings.List.ListMargin
  langs:
  - csharp
  - vb
  name: List
  nameWithType: List
  fullName: Quokka.Settings.List
  type: Class
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: List
    path: ../Quokka/Settings/Settings.cs
    startLine: 76
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public class List
    content.vb: Public Class List
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quokka.Settings.List.ListMargin
  commentId: P:Quokka.Settings.List.ListMargin
  id: ListMargin
  parent: Quokka.Settings.List
  langs:
  - csharp
  - vb
  name: ListMargin
  nameWithType: List.ListMargin
  fullName: Quokka.Settings.List.ListMargin
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListMargin
    path: ../Quokka/Settings/Settings.cs
    startLine: 78
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ListMargin { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ListMargin As String
  overload: Quokka.Settings.List.ListMargin*
- uid: Quokka.Settings.List.ContentHorizontalAlignment
  commentId: P:Quokka.Settings.List.ContentHorizontalAlignment
  id: ContentHorizontalAlignment
  parent: Quokka.Settings.List
  langs:
  - csharp
  - vb
  name: ContentHorizontalAlignment
  nameWithType: List.ContentHorizontalAlignment
  fullName: Quokka.Settings.List.ContentHorizontalAlignment
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ContentHorizontalAlignment
    path: ../Quokka/Settings/Settings.cs
    startLine: 79
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ContentHorizontalAlignment { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ContentHorizontalAlignment As String
  overload: Quokka.Settings.List.ContentHorizontalAlignment*
- uid: Quokka.Settings.List.ButtonContentMargin
  commentId: P:Quokka.Settings.List.ButtonContentMargin
  id: ButtonContentMargin
  parent: Quokka.Settings.List
  langs:
  - csharp
  - vb
  name: ButtonContentMargin
  nameWithType: List.ButtonContentMargin
  fullName: Quokka.Settings.List.ButtonContentMargin
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ButtonContentMargin
    path: ../Quokka/Settings/Settings.cs
    startLine: 80
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ButtonContentMargin { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ButtonContentMargin As String
  overload: Quokka.Settings.List.ButtonContentMargin*
- uid: Quokka.Settings.List.ListItems
  commentId: P:Quokka.Settings.List.ListItems
  id: ListItems
  parent: Quokka.Settings.List
  langs:
  - csharp
  - vb
  name: ListItems
  nameWithType: List.ListItems
  fullName: Quokka.Settings.List.ListItems
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ListItems
    path: ../Quokka/Settings/Settings.cs
    startLine: 81
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public ListItems ListItems { get; set; }
    parameters: []
    return:
      type: Quokka.Settings.ListItems
    content.vb: Public Property ListItems As ListItems
  overload: Quokka.Settings.List.ListItems*
references:
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  href: Quokka.html
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  spec.csharp:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
  spec.vb:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quokka.Settings.List.ListMargin*
  commentId: Overload:Quokka.Settings.List.ListMargin
  href: Quokka.Settings.List.html#Quokka_Settings_List_ListMargin
  name: ListMargin
  nameWithType: List.ListMargin
  fullName: Quokka.Settings.List.ListMargin
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Quokka.Settings.List.ContentHorizontalAlignment*
  commentId: Overload:Quokka.Settings.List.ContentHorizontalAlignment
  href: Quokka.Settings.List.html#Quokka_Settings_List_ContentHorizontalAlignment
  name: ContentHorizontalAlignment
  nameWithType: List.ContentHorizontalAlignment
  fullName: Quokka.Settings.List.ContentHorizontalAlignment
- uid: Quokka.Settings.List.ButtonContentMargin*
  commentId: Overload:Quokka.Settings.List.ButtonContentMargin
  href: Quokka.Settings.List.html#Quokka_Settings_List_ButtonContentMargin
  name: ButtonContentMargin
  nameWithType: List.ButtonContentMargin
  fullName: Quokka.Settings.List.ButtonContentMargin
- uid: Quokka.Settings.List.ListItems*
  commentId: Overload:Quokka.Settings.List.ListItems
  href: Quokka.Settings.List.html#Quokka_Settings_List_ListItems
  name: ListItems
  nameWithType: List.ListItems
  fullName: Quokka.Settings.List.ListItems
- uid: Quokka.Settings.ListItems
  commentId: T:Quokka.Settings.ListItems
  parent: Quokka.Settings
  href: Quokka.Settings.ListItems.html
  name: ListItems
  nameWithType: ListItems
  fullName: Quokka.Settings.ListItems
