### YamlMime:ManagedReference
items:
- uid: Quokka.Settings.Details
  commentId: T:Quokka.Settings.Details
  id: Details
  parent: Quokka.Settings
  children:
  - Quokka.Settings.Details.ContentHorizontalAlignment
  - Quokka.Settings.Details.ContentMargin
  - Quokka.Settings.Details.ContentVerticalAlignment
  - Quokka.Settings.Details.FontFamily
  - Quokka.Settings.Details.ImageMargin
  - Quokka.Settings.Details.TextColor
  - Quokka.Settings.Details.TextLineMargin
  - Quokka.Settings.Details.TextSize
  langs:
  - csharp
  - vb
  name: Details
  nameWithType: Details
  fullName: Quokka.Settings.Details
  type: Class
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: Details
    path: ../Quokka/Settings/Settings.cs
    startLine: 41
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public class Details
    content.vb: Public Class Details
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quokka.Settings.Details.ContentMargin
  commentId: P:Quokka.Settings.Details.ContentMargin
  id: ContentMargin
  parent: Quokka.Settings.Details
  langs:
  - csharp
  - vb
  name: ContentMargin
  nameWithType: Details.ContentMargin
  fullName: Quokka.Settings.Details.ContentMargin
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ContentMargin
    path: ../Quokka/Settings/Settings.cs
    startLine: 43
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ContentMargin { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ContentMargin As String
  overload: Quokka.Settings.Details.ContentMargin*
- uid: Quokka.Settings.Details.ContentVerticalAlignment
  commentId: P:Quokka.Settings.Details.ContentVerticalAlignment
  id: ContentVerticalAlignment
  parent: Quokka.Settings.Details
  langs:
  - csharp
  - vb
  name: ContentVerticalAlignment
  nameWithType: Details.ContentVerticalAlignment
  fullName: Quokka.Settings.Details.ContentVerticalAlignment
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ContentVerticalAlignment
    path: ../Quokka/Settings/Settings.cs
    startLine: 44
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ContentVerticalAlignment { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ContentVerticalAlignment As String
  overload: Quokka.Settings.Details.ContentVerticalAlignment*
- uid: Quokka.Settings.Details.ContentHorizontalAlignment
  commentId: P:Quokka.Settings.Details.ContentHorizontalAlignment
  id: ContentHorizontalAlignment
  parent: Quokka.Settings.Details
  langs:
  - csharp
  - vb
  name: ContentHorizontalAlignment
  nameWithType: Details.ContentHorizontalAlignment
  fullName: Quokka.Settings.Details.ContentHorizontalAlignment
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ContentHorizontalAlignment
    path: ../Quokka/Settings/Settings.cs
    startLine: 45
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ContentHorizontalAlignment { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ContentHorizontalAlignment As String
  overload: Quokka.Settings.Details.ContentHorizontalAlignment*
- uid: Quokka.Settings.Details.ImageMargin
  commentId: P:Quokka.Settings.Details.ImageMargin
  id: ImageMargin
  parent: Quokka.Settings.Details
  langs:
  - csharp
  - vb
  name: ImageMargin
  nameWithType: Details.ImageMargin
  fullName: Quokka.Settings.Details.ImageMargin
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: ImageMargin
    path: ../Quokka/Settings/Settings.cs
    startLine: 46
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string ImageMargin { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ImageMargin As String
  overload: Quokka.Settings.Details.ImageMargin*
- uid: Quokka.Settings.Details.TextColor
  commentId: P:Quokka.Settings.Details.TextColor
  id: TextColor
  parent: Quokka.Settings.Details
  langs:
  - csharp
  - vb
  name: TextColor
  nameWithType: Details.TextColor
  fullName: Quokka.Settings.Details.TextColor
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: TextColor
    path: ../Quokka/Settings/Settings.cs
    startLine: 47
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string TextColor { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TextColor As String
  overload: Quokka.Settings.Details.TextColor*
- uid: Quokka.Settings.Details.TextSize
  commentId: P:Quokka.Settings.Details.TextSize
  id: TextSize
  parent: Quokka.Settings.Details
  langs:
  - csharp
  - vb
  name: TextSize
  nameWithType: Details.TextSize
  fullName: Quokka.Settings.Details.TextSize
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: TextSize
    path: ../Quokka/Settings/Settings.cs
    startLine: 48
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string TextSize { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TextSize As String
  overload: Quokka.Settings.Details.TextSize*
- uid: Quokka.Settings.Details.FontFamily
  commentId: P:Quokka.Settings.Details.FontFamily
  id: FontFamily
  parent: Quokka.Settings.Details
  langs:
  - csharp
  - vb
  name: FontFamily
  nameWithType: Details.FontFamily
  fullName: Quokka.Settings.Details.FontFamily
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: FontFamily
    path: ../Quokka/Settings/Settings.cs
    startLine: 49
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string FontFamily { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FontFamily As String
  overload: Quokka.Settings.Details.FontFamily*
- uid: Quokka.Settings.Details.TextLineMargin
  commentId: P:Quokka.Settings.Details.TextLineMargin
  id: TextLineMargin
  parent: Quokka.Settings.Details
  langs:
  - csharp
  - vb
  name: TextLineMargin
  nameWithType: Details.TextLineMargin
  fullName: Quokka.Settings.Details.TextLineMargin
  type: Property
  source:
    remote:
      path: Quokka/Settings/Settings.cs
      branch: feature-ContextPanes
      repo: git@github.com:Faeq-F/Quokka.git
    id: TextLineMargin
    path: ../Quokka/Settings/Settings.cs
    startLine: 50
  assemblies:
  - Quokka
  namespace: Quokka.Settings
  syntax:
    content: public string TextLineMargin { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TextLineMargin As String
  overload: Quokka.Settings.Details.TextLineMargin*
references:
- uid: Quokka.Settings
  commentId: N:Quokka.Settings
  href: Quokka.html
  name: Quokka.Settings
  nameWithType: Quokka.Settings
  fullName: Quokka.Settings
  spec.csharp:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
  spec.vb:
  - uid: Quokka
    name: Quokka
    href: Quokka.html
  - name: .
  - uid: Quokka.Settings
    name: Settings
    href: Quokka.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quokka.Settings.Details.ContentMargin*
  commentId: Overload:Quokka.Settings.Details.ContentMargin
  href: Quokka.Settings.Details.html#Quokka_Settings_Details_ContentMargin
  name: ContentMargin
  nameWithType: Details.ContentMargin
  fullName: Quokka.Settings.Details.ContentMargin
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Quokka.Settings.Details.ContentVerticalAlignment*
  commentId: Overload:Quokka.Settings.Details.ContentVerticalAlignment
  href: Quokka.Settings.Details.html#Quokka_Settings_Details_ContentVerticalAlignment
  name: ContentVerticalAlignment
  nameWithType: Details.ContentVerticalAlignment
  fullName: Quokka.Settings.Details.ContentVerticalAlignment
- uid: Quokka.Settings.Details.ContentHorizontalAlignment*
  commentId: Overload:Quokka.Settings.Details.ContentHorizontalAlignment
  href: Quokka.Settings.Details.html#Quokka_Settings_Details_ContentHorizontalAlignment
  name: ContentHorizontalAlignment
  nameWithType: Details.ContentHorizontalAlignment
  fullName: Quokka.Settings.Details.ContentHorizontalAlignment
- uid: Quokka.Settings.Details.ImageMargin*
  commentId: Overload:Quokka.Settings.Details.ImageMargin
  href: Quokka.Settings.Details.html#Quokka_Settings_Details_ImageMargin
  name: ImageMargin
  nameWithType: Details.ImageMargin
  fullName: Quokka.Settings.Details.ImageMargin
- uid: Quokka.Settings.Details.TextColor*
  commentId: Overload:Quokka.Settings.Details.TextColor
  href: Quokka.Settings.Details.html#Quokka_Settings_Details_TextColor
  name: TextColor
  nameWithType: Details.TextColor
  fullName: Quokka.Settings.Details.TextColor
- uid: Quokka.Settings.Details.TextSize*
  commentId: Overload:Quokka.Settings.Details.TextSize
  href: Quokka.Settings.Details.html#Quokka_Settings_Details_TextSize
  name: TextSize
  nameWithType: Details.TextSize
  fullName: Quokka.Settings.Details.TextSize
- uid: Quokka.Settings.Details.FontFamily*
  commentId: Overload:Quokka.Settings.Details.FontFamily
  href: Quokka.Settings.Details.html#Quokka_Settings_Details_FontFamily
  name: FontFamily
  nameWithType: Details.FontFamily
  fullName: Quokka.Settings.Details.FontFamily
- uid: Quokka.Settings.Details.TextLineMargin*
  commentId: Overload:Quokka.Settings.Details.TextLineMargin
  href: Quokka.Settings.Details.html#Quokka_Settings_Details_TextLineMargin
  name: TextLineMargin
  nameWithType: Details.TextLineMargin
  fullName: Quokka.Settings.Details.TextLineMargin
